App/LoadImage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('threshold/', views.thresholdOp),
    path('colors/', views.color_range),
    path('streaming/', views.streaming_webcam),
    path('webcam_feed/',views.webcam_feed, name = 'webcam_feed'),
]

ImageManipulationGUI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.LoadImage.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/LoadImage/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    image2analysis = models.ImageField(verbose_name='Cargar Imagen: ', null=True, blank=True, upload_to='images/')

    def save(self, *args, **kwargs):
        # delete old file when replacing by updating the file
        try:
            actualImage = Image.objects.get(id=self.id)
            actualImage.image2analysis.delete()
        except: 
            pass # when new photo then we do nothing, normal case          
        super().save(*args, **kwargs)

    def __str__(self):
        return f'({self.id}) Image uploaded at: '+ str(self.image2analysis)

class ThresholdData(models.Model):
    upperThres = models.IntegerField(verbose_name='Upper Threshold: ', null=True, blank=True)
    lowerThres = models.IntegerField(verbose_name='Lower Threshold: ', null=True, blank=True)

    def __str__(self):
        return f'Upper: {self.upperThres}, Lower: {self.lowerThres}'

App/LoadImage/forms.py
from django import forms
from django.forms import ModelForm
from .models import Image, ThresholdData

class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ('image2analysis',)

class ThresholdForm(ModelForm):
    
    class Meta:
        model = ThresholdData
        fields = ('upperThres', 'lowerThres', )
        widgets = {
            'upperThres': forms.TextInput(attrs={'onChange': 'form.submit();',
                                                        'type':'range', 'min': 0, 'max': 255, 'step': 1}
                                                ),
            'lowerThres': forms.TextInput(attrs={'onChange': 'form.submit();',
                                                        'type':'range', 'min': 0, 'max': 255, 'step': 1, 'value':0}
                                                ),
        }


class HSVRangeForm(forms.Form):
    hu = forms.CharField(
            label = 'Hue Top',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'range', 'min': 0, 'max': 180, 'step': 1, 
                        ':value': 'huValue', 'v-on:input':"huValue = $event.target.value",
                        }
                )
            )
    huBox = forms.CharField(
            label = '',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'number', 'min': 0, 'max': 180, 'step': 1,
                        ':value': 'huValue', 'v-on:input':"huValue = $event.target.value",
                        }
                )
        )
    hl = forms.CharField(
            label = 'Hue Bottom',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'range', 'min': 0, 'max': 180, 'step': 1, 
                        ':value': 'hlValue', 'v-on:input':"hlValue = $event.target.value",
                        }
                )
            )

    hlBox = forms.CharField(
            label = '',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'number', 'min': 0, 'max': 180, 'step': 1,
                        ':value': 'hlValue', 'v-on:input':"hlValue = $event.target.value",
                        }
                )
        )

    su = forms.CharField(
            label = 'Saturation Top',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'range', 'min': 0, 'max': 255, 'step': 1,  
                        ':value': 'suValue', 'v-on:input':"suValue = $event.target.value",
                        }
                )
            )

    suBox = forms.CharField(
            label = '',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'number', 'min': 0, 'max': 180, 'step': 1,
                        ':value': 'suValue', 'v-on:input':"suValue = $event.target.value",
                        }
                )
        )

    sl = forms.CharField(
            label = 'Saturation Bottom',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'range', 'min': 0, 'max': 255, 'step': 1, 
                        ':value': 'slValue', 'v-on:input':"slValue = $event.target.value",
                        }
                )
            )
    
    slBox = forms.CharField(
            label = '',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'number', 'min': 0, 'max': 180, 'step': 1,
                        ':value': 'slValue', 'v-on:input':"slValue = $event.target.value",
                        }
                )
        )

    vu = forms.CharField(
            label = 'Value Top',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'range', 'min': 0, 'max': 255, 'step': 1, 
                        ':value': 'vuValue', 'v-on:input':"vuValue = $event.target.value",
                        }
                )
            )

    vuBox = forms.CharField(
            label = '',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'number', 'min': 0, 'max': 180, 'step': 1,
                        ':value': 'vuValue', 'v-on:input':"vuValue = $event.target.value",
                        }
                )
        )
    
    vl = forms.CharField(
            label = 'Value Bottom',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'range', 'min': 0, 'max': 255, 'step': 1, 
                        ':value': 'vlValue', 'v-on:input':"vlValue = $event.target.value",
                        }
                )
            )

    vlBox = forms.CharField(
            label = '',
            widget=forms.TextInput(
                attrs={'onChange': 'form.submit();', 'type':'number', 'min': 0, 'max': 180, 'step': 1,
                        ':value': 'vlValue', 'v-on:input':"vlValue = $event.target.value",
                        }
                )
        )

App/LoadImage/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.http import HttpRequest
from django.http.response import StreamingHttpResponse
from django.template import Template, Context
from django.core.files.storage import FileSystemStorage
from django.core.files.base import ContentFile
from django.conf import settings
from .models import Image, ThresholdData
from .forms import ImageForm, ThresholdForm, HSVRangeForm
from App.LoadImage.BasicImageProcessing.basic_ip import *
from .camera import Webcam

import os
import datetime
import cv2
import numpy as np



TEMPLATES = os.path.join(os.getcwd(),'App/LoadImage/templates')


# Funciones y clases chimbitas

def save_imageArray_to_model(imgArray):
    _,imEncoded = cv2.imencode('.png',imgArray)
    imgfile = ContentFile(imEncoded)
    editableImage = Image.objects.get(id=3)
    editableImage.image2analysis.save('actual_edit.png', imgfile, save=True)




# Metodos de vistas 

def home(request: HttpRequest): # Vista
    form = ImageForm()
    if request.method == "POST":
        actualImage = Image.objects.get(id=2)
        editImage = Image.objects.get(id= 3)
        formUpdate = ImageForm(request.POST,request.FILES,instance = actualImage)
        formEditImg = ImageForm(request.POST,request.FILES,instance = editImage)
        if formUpdate.is_valid() and formEditImg.is_valid():
            formUpdate.save()
            formEditImg.save()
        updatedImage = Image.objects.get(id=2)
    else:
        updatedImage = Image.objects.get(id=2)
        
    return render(request, 'loadImg.html', {'form': form, 'image':updatedImage})

def thresholdOp(request: HttpRequest):
    tform = ThresholdForm()
    upperThres = None
    lowerThres = 0
    if request.method == 'POST':
        tform = ThresholdForm(request.POST)
        if tform.is_valid():
            upperThres = int(request.POST['upperThres'])
            lowerThres = int(request.POST['lowerThres'])

            tform.save(commit=False)

    originalImage = Image.objects.get(id=2)
    img2edit = cv2.imread(originalImage.image2analysis.path)
    if img2edit is not None and upperThres is not None:
        # TODO: Terminar código para mostrar el historial de la imagen con las barras denotando el rango usado
        #histr = cv2.calcHist([img2edit],[0],None,[256],[0,256])
        ######################################################
        imgProcessor = ImageProcessor(img2edit)
        imgProcessor.turn_image_to_gray()
        editedImg = imgProcessor.apply_range(upperThres, lowerThres, getMask=True)
        save_imageArray_to_model(editedImg)

    updatedImage = Image.objects.get(id=3)
    return render(request, 'thresholdPage.html', {'form':tform, 'image': updatedImage,})
    
def color_range(request: HttpRequest):
    if request.method == 'POST':
        hsvform = HSVRangeForm(request.POST)
        if hsvform.is_valid():
            hu = int(request.POST['hu'])
            su = int(request.POST['su'])
            vu = int(request.POST['vu'])
            hl = int(request.POST['hl'])
            sl = int(request.POST['sl'])
            vl = int(request.POST['vl'])

            originalImage = Image.objects.get(id=2)

            imgProcessor = ImageProcessor (cv2.imread(originalImage.image2analysis.path))
            imgProcessor.turn_image_to_HSV()
            imgProcessor.apply_range([hu,su,vu],[hl,sl,vl],inner=False)
            hsvFiltered = imgProcessor.get_image_procesed()


            save_imageArray_to_model(hsvFiltered)

    else:
        hu = 180
        su = 255
        vu = 255
        hl = 0
        sl = 0
        vl = 0
        hsvform = HSVRangeForm()
    
    updatedImage = Image.objects.get(id=3)

    values = {
        'hu':hu,
        'su':su,
        'vu':vu,
        'hl':hl,
        'sl':sl,
        'vl':vl,
    }

    
    return render(request, 'colorRanges.html', {'form':hsvform, 'image': updatedImage, 'values':values})



def streaming_webcam (request):
    return render(request, 'streaming.html')

def gen(camera):
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
                b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


def webcam_feed (request):
    return StreamingHttpResponse(gen(Webcam()),
                                    content_type ='multipart/x-mixed-replace; boundary=frame')

App/LoadImage/templates/colorRanges.html
{% extends "./base.html" %}

{%block title %}Img 360°: Color{% endblock %}
{% block body%}
    <center>
        <h1>Color Range</h1>
    </center>
    <center>
        <div class="row m-3">
            <div style='text-align:right' class='col-sm-12 col-md-6 col-lg-4 col-xl-4' id='app'>
                <left>
                    <form method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <!-- <p>
                            <label for="id_hu">Hue Top:</label> 
                            <input type="range" onchange="form.submit();" name="hu"
                                    min="0" max="180" step="1" id="id_hu"
                                    :value=huValue v-on:input="huValue = $event.target.value" >
                        </p>
                        <p>
                            <input  type="number" name="huBox" min="0" max="180" step="1" id="id_huBox" 
                                    :value=huValue v-on:input="huValue = $event.target.value">
                        </p> -->
                        {{form.as_p}}
                        <!-- <button type="submit" class="btn btn-secondary">Submit</button> -->
                        <br>
                    </form>
                </left>
            </div>
        
            <div class='col-sm-12 col-md-6 col-lg-8 col-xl-8'>
                <img src="{{image.image2analysis.url}}"  align="center" width = 500 >
            </div>
        </div>
    </center>
    <script type="text/javascript">
        const app = new Vue({
            el: '#app',
            data: {
                huValue: {{values.hu}},
                suValue: {{values.su}},
                vuValue: {{values.vu}},
                hlValue: {{values.hl}},
                slValue: {{values.sl}},
                vlValue: {{values.vl}},
            }

        })

    </script>
{% endblock %}

App/LoadImage/templates/loadImg.html
{% extends "./base.html" %}

{%block title %}Img 360°: Load{% endblock %}

{% block body%}
    <center>
        <h1>Cargar imagen</h1>
    </center>
    <center>
        <div class="row m-3">
            <div class='col-sm-12 col-md-6 col-lg-4 col-xl-4'>
                <center>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-secondary">Submit</button>
                        <br>
                    </form>
                </center>
            </div>
        
            <div class='col-sm-12 col-md-6 col-lg-8 col-xl-8'>
                <img src="{{image.image2analysis.url}}"  align="center" width = 500>
            </div>
        </div>
    </center>
    
{% endblock %}

App/LoadImage/templates/streaming.html
{% extends "./base.html" %}

{%block title %}Img 360°: Webcam{% endblock %}
{% block body%}
    <center>
        <h1>Webcam</h1>
    </center>
    <center>
        <div class="row m-3">
            <img src="{% url 'webcam_feed' %}" width = 500>
        </div>
    </center>
    
{% endblock %}

App/LoadImage/templates/thresholdPage.html
{% extends "./base.html" %}

{%block title %}Img 360°: Threshold{% endblock %}
{% block body%}
    <center>
        <h1>Threshold</h1>
    </center>
    <center>
        <div class="row m-3">
            <div class='col-sm-12 col-md-6 col-lg-4 col-xl-4'>
                <center>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <!-- <button type="submit" class="btn btn-secondary">Submit</button> -->
                        <br>
                    </form>
                </center>
            </div>
        
            <div class='col-sm-12 col-md-6 col-lg-8 col-xl-8'>
                <img src="{{image.image2analysis.url}}"  align="center" width = 500 >
                {{editedImg}}
            </div>
        </div>
    </center>
{% endblock %}